version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
        ports:
            - "5432:5432"

    web:
        build: .
        command: >
            sh -c "python create_tables.py && python script.py && python app.py"
        env_file:
            - ./.env
        ports:
            - "5000:5000"
        depends_on:
            - db


volumes:
    postgres_data:
