version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        env_file:
            - ../.env
        ports:
            - "5432:5432"

    web:
        build: ..
        command: >
            sh -c "python app.py"
        volumes:
            - ./static:/home/danii/web/static
        env_file:
            - ../.env
        ports:
            - "6666:6666"
        depends_on:
            - db


volumes:
    postgres_data:
